pluginManagement {
    repositories {
        mavenCentral()
        maven { url = uri("https://repo.spring.io/release") }
        gradlePluginPortal()
        maven { url = uri("https://plugins.gradle.org/m2") }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "org.springframework.boot") {
                useModule("org.springframework.boot:spring-boot-gradle-plugin:${requested.version}")
            }
            if (requested.id.id == "io.spring.dependency-management") {
                useModule("io.spring.gradle:dependency-management-plugin:${requested.version}")
            }
        }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = uri("https://repo.spring.io/release") }
    }
}

rootProject.name = "backend"
